title: My Optics & R&D Portfolio
email: your.email@example.com
description: >- 
  A futuristic yet minimal academic-style portfolio showcasing optics research, consulting work, and science communication.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
